### ISSUE TITLE
Eloquent Bloom Release

### ISSUE THREAD

**Issue by IanTheEngineer** [ros2-gbp/librealsense-release#1]
It would be appreciated to have the same `librealsense2` that was released in dashing available in eloquent, if possible (continuing to utilize the older but functional `ros2debian` branch):
https://github.com/ros/rosdistro/pull/21240
https://github.com/ros/rosdistro/pull/21267
https://github.com/ros/rosdistro/pull/23461

@RachelRen05, @tfoote, and @doronhi is this possible? Would we need signoff from someone at Intel?

**Comment by doronhi** [comment]
As this is something that is pretty much off the table for me, anyone who picks it up has my approval and blessings.

**Comment by nuclearsandwich** [comment]
Since Eloquent is no longer supported I am going to close this issue.
